In [1]:
import numpy as np

# 1. Broadcasting

### a) Add a 1D array `[1, 2, 3]` to each row of a 2D array `[[10, 20, 30], [40, 50, 60]]`.
#### Expected: [[11, 22, 33], [41, 52, 63]]

In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

In [18]:
print(arr1 + arr2)

[[11 22 33]
 [41 52 63]]


### b) Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise.
#### Expected: [[10, 20], [60, 80]]

In [25]:
arr1 = np.array([10, 20]).reshape(2,-1)
arr2 = np.array([[1, 2], [3, 4]])

In [26]:
print(arr1 * arr2)

[[10 20]
 [60 80]]


# 2. Indexing and Slicing (High Dimensional Arrays)

In [32]:
arr = np.arange(1, 25).reshape(2, 3, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### a) Extract the second slice along axis 0.
#### Expected: [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]

In [30]:
arr[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

### b) Extract all rows and the last column for all slices.
#### Expected: [[4, 8, 12], [16, 20, 24]]

In [31]:
arr[:,:,-1]

array([[ 4,  8, 12],
       [16, 20, 24]])

### c) Reverse the order of slices along axis 0.
#### Expected: [[[13, 14, 15, 16], ...], [[1, 2, 3, 4], ...]]

In [41]:
arr[::-1]

array([[[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

### d) Set all even elements in the array to -1.
#### Expected: All even numbers replaced by -1.

In [44]:
arr[:] = -1
arr

array([[[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]],

       [[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]]])

# 3. np.repeat

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

### a) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where every odd element is repeated twice.
#### Expected: [1, 1, 3, 3, 5, 5]

In [46]:
repeats = np.where(arr % 2 == 1, 2, 1)
repeats

array([2, 1, 2, 1, 2, 1])

In [47]:
result = np.repeat(arr, repeats)
result

array([1, 1, 2, 3, 3, 4, 5, 5, 6])

### b) Given `arr = np.array([1, 2, 3, 4, 5, 6])`, create a new array where elements are repeated based on their value.
#### For example, `1` is repeated once, `2` twice, etc.
#### Expected: [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, ...]

In [49]:
result = np.repeat(arr,arr)
result

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6])

# 4. Normalizing

In [58]:
arr = np.array([10, 20, 30])

### a) Normalize a 1D array `arr = np.array([10, 20, 30])` to have values between 0 and 1.
#### Expected: [0.0, 0.5, 1.0]

In [59]:
min = np.min(arr)
min

10

In [60]:
max = np.max(arr)
max

30

In [61]:
arr_norm = (arr - min)/(max - min)
arr_norm

array([0. , 0.5, 1. ])

# 5. Bonus Challenge

### a) Create a 3x3 matrix where each element at position (i, j) is i * j.
#### Expected: [[0, 0, 0], [0, 1, 2], [0, 2, 4]]

In [68]:
arr = np.zeros((3,3), dtype=int)
for i in range(3):
    for j in range(3):
        arr[i,j] = i*j

arr

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

### b) Given a 4x4 matrix, replace all elements on the main diagonal with 0 without using a loop.
#### Expected: Diagonal elements replaced with 0.

In [74]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
np.fill_diagonal(arr, 0)
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])